import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "primereact/resources/themes/lara-light-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import { PrimeReactProvider } from "primereact/api";
import FooterSection from "@/components/footer/footer";
import Navbar from "@/components/layout/navbar/Navbar";
import { FeeSelectionProvider } from "@/context/FeeSelectionContext";
import { AuthProvider } from "@/context/AuthContext";
import "@fortawesome/fontawesome-free/css/all.min.css";


import FloatingContactButtons from "@/components/layout/contact/FloatingContactButtons";

export const metadata: Metadata = {
  title: "ChangeXpert",
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          <AuthProvider>
            <FeeSelectionProvider>
              <Navbar />
              {children}
              <FooterSection />
              <FloatingContactButtons />
            </FeeSelectionProvider>
          </AuthProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
